# Generated by Django 4.2.4 on 2023-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_branch_name_alter_branch_smartup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='smartup_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='smartup_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='smartup_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
