# Generated by Django 4.2.4 on 2023-08-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_payment_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="date_of_payment",
            field=models.DateField(auto_now=True),
        ),
    ]
