# Generated by Django 4.2.4 on 2023-08-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_payment_date_of_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="date_of_order",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="date_of_shipment",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.payment",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
