# Generated by Django 4.2.4 on 2023-08-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deal_date_of_order_deal_date_of_shipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='payment',
        ),
        migrations.AddField(
            model_name='deal',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymenttype'),
        ),
    ]
