# Generated by Django 4.2.4 on 2023-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_of_order',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_of_shipment',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(),
        ),
    ]
