# Generated by Django 4.2.4 on 2023-08-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_workplace"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workplace",
            old_name="assigned_users",
            new_name="customers",
        ),
        migrations.AddField(
            model_name="workplace",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
