# Generated by Django 4.2.11 on 2024-04-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_rename_assigned_users_workplace_customers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("message_content", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
